# Generated by Django 4.2.7 on 2023-11-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='slug',
        ),
    ]
