# Generated by Django 4.2.7 on 2023-11-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_chatroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='slug',
            field=models.SlugField(default='exit', unique=True),
            preserve_default=False,
        ),
    ]
